### ISSUE TITLE
the command of ucp replica join into ucp controller  is not idempotent

### ISSUE THREAD

**Issue by panyufeng920** [grahamnscp/ansible-ddc-deploy-centos7#1]

**Comment by grahamnscp** [comment]
Hi panyufeng920, thanks for the comment, I may have changed the code since then but the ansible creates shouldn't run if the log file exists.  The main issue with this approach is that if it fails you have to manually remove the log file for it to try again:

- name: "Join replica to cluster"
  shell: /bin/docker swarm join --token {{ hostvars[groups['ucp-primary'][0]]['master_token'].stdout }} {{ hostvars[groups['ucp-primary'][0]]['ansible_eth0']['ipv4']['address'] }} 2>&1 | /bin/tee -a /root/swarm-replica-join.log
  args:
    creates: /root/swarm-replica-join.log
